### ISSUE TITLE
Possible unsoundness in the C/C++ interface

### ISSUE THREAD

**Issue by jonasmalacofilho** [timClicks/ulid-lite#6]
Hi,

I saw your tweet asking for opinions on how ergonomic the C/C++ API is, and while I'm not well suited to answer that, I wanted to see how you implemented this library.  While taking a look at the code, I think I may have accidentally spotted a couple of problems.<sup>1</sup>

The first is that `ulid_new()` appears to return a pointer to the stack: it creates a new `Ulid` on the stack, transmutes it to a `UlidArray`, and returns a pointer to it.  There are no allocations, so isn't that a pointer to the stack and, more importantly, a pointer that becomes invalid as soon as that function returns?  [Miri seems to agree](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5e5b5497c41674da606d070c32984725).

Another issue, is that in `ulid_new_string()` the returned pointer is derived from a temporary `String` (created with `Ulid::new().to_string()`), which is immediately dropped, making the pointer invalid.  [Miri also seems to agree](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4b1ff3a456db3256a3632bc345a87e90).

That string is also allocated with Rust's Global allocator, so it's probably not sound to free it with any other allocator.

As a minor final observation, the function transmutes a `const` pointer into a mutable one.  This is (probably) fine in that instance, as at that point we own the value anyway, but wouldn't `as_mut_ptr()` be a bit more direct?

--- 

P.S. The Miri examples used a simplified implementation to avoid calling functions from `libc`, which Miri doesn't yet support.

_<sup>1</sup> I'm pretty new to Rust, and even more so to unsafe Rust.  So I'm sorry if I'm missing something obvious..._

**Comment by timClicks** [comment]
Thanks for these comments @jonasmalacofilho. Your analysis is correct - I am very tempted to yank the commits that provide the interface, actually. I should be able to get (significant) improvements to the code over the weekend though and don't believe anyone's relying on this - so I'll keep things up as-is for the moment. Thanks again.

**Comment by timClicks** [comment]
Fixed by c6c5345110b5c0a71f94d8c75029ef68b2688d3a

Thanks again for investigating and reporting the issue!
