### ISSUE TITLE
libc's rand not thread-safe

### ISSUE THREAD

**Issue by timClicks** [timClicks/ulid-lite#8]
In multi-threaded environments, the current code won't behave properly. Multiple threads can created the same ID.

From the [rand(3) manpage](https://man7.org/linux/man-pages/man3/rand.3.html): 

> The function `rand()` is not reentrant, since it uses hidden state 
> that is modified on each call.  This might just be the seed value 
> to be used by the next call, or it might be something more
> elaborate.  In order to get reproducible behavior in a threaded
> application, this state must be made explicit; this can be done
> using the reentrant function `rand_r()`.

The difficulty in deciding what to do is that I would prefer to avoid Linux-specific APIs. So perhaps a stopgap would be a semaphore/spinlock. In the worst case, this would stall other threads for ~20 nanoseconds.

**Comment by jonasmalacofilho** [comment]
What if different RNGs where used for each thread, either using TLS (like the `rand` crate offers) or requiring the user to keep some `!Sync` "context" value?

On a related note, `libc::rand()` can be a [very simple](https://git.musl-libc.org/cgit/musl/tree/src/prng/rand.c) RNG... perhaps too simple even.

**Comment by timClicks** [comment]
I did some research on this today and learned that `rand_r` is part of the POSIX standard (and that `rand` is actually deprecated). The fastest way forward would be to use that. [Edit: Naturally, `rand_r()` is not exposed by the `libc` crate.]

I am tempted to include an RNG in the source to avoid libc and allow the crate to be used in no_std environments.

Having a thread-local RNG could work too.. Marking the context object as !Sync sounds like a good idea

I will do some research.

**Comment by jonasmalacofilho** [comment]
Besides `rand_r()` not being exposed by the `libc` crate, it's limited to a rather small  state (one `unsigned int`).  This wasn't immediately obvious to me, but I saw it mentioned in a couple of online man pages.

I also saw a mention of `rand_r()` already bring deprecated in a later POSIX, but haven't been able to verify that yet.

Still, each ULID needs 80 bits of randomness, and the spec recommends a crypto-secure RNG (when possible).  It might be that `rand_r()` and `rand()` (especially considering implementations like musl's) are not a very good fit here.

**Comment by jonasmalacofilho** [comment]
I did a quick test, _just to have a reference,_ and using the `rand` crate in the most trivial way possible doesn't perform that much worse, even in the compilation time.  And it's even a tiny bit faster at runtime.

Using `(libc::rand(), libc::rand(), libc::rand())`:

```
$ cargo b --release
[...]
    Finished release [optimized] target(s) in 3.51s
    
$ cargo bench
[...]
test benchmark_generation ... bench:          32 ns/iter (+/- 0)
test benchmark_serialized ... bench:          76 ns/iter (+/- 0)
[...]
```

Using `(rand::random::<u64>(), rand::random::<u16>()`:

```
$ cargo b --release
[...]
    Finished release [optimized] target(s) in 4.58s
    
$ cargo bench
[...]
test benchmark_generation ... bench:          27 ns/iter (+/- 0)
test benchmark_serialized ... bench:          73 ns/iter (+/- 0)
[...]
```

---

EDIT: the compilation time shown in the README appears to be from before you enabled `lto` (I can reproduce it by disabling it).
